// ============================================================
// Digital Profile — Avinash Upadhyay
// Generated by BuildwithAiGiri x IntelliForge AI
// https://www.intelliforge.tech/
// ============================================================

export const personalInfo = {
  name: "Avinash Upadhyay",
  initials: "AU",
  title: "Co-founder & Strategy Lead — Cheerio AI",
  tagline: "8+ Years · Enterprise SaaS · AI Startup Founder · XLRI MBA · ₹8Cr Seed Raised",
  summary:
    "Entrepreneur and strategy leader building the future of agentic AI for enterprise. Co-founded Cheerio AI — an AI-first workflow platform serving 150+ enterprises across marketing, sales, support, and retention. Previously built go-to-market and consulting expertise at Darwinbox, Coforge, and ADPL. XLRI MBA with deep roots in strategic management and MIS.",
  aiSummary:
    "I'm Avinash — a founder and operator at the intersection of enterprise SaaS and agentic AI. I co-built Cheerio AI from scratch, raised ₹8 Crore in seed funding, and now serve 150+ enterprise customers who've generated ₹500+ Crore in additional revenue using our platform. Before Cheerio, I honed my strategy and consulting instincts at Darwinbox, Coforge, and ADPL. Ask me about AI workflows, B2B SaaS go-to-market, or building and scaling enterprise AI products.",
  currentPursuit:
    "Scaling Cheerio AI to become the definitive agentic AI platform for enterprise workflows across Asia",
  location: "Bengaluru, Karnataka, India",
  linkedin: "https://www.linkedin.com/in/avinashupadhyay24",
  github: "",
  email: "avinash@cheerioai.com",
};

export const stats = [
  { label: "Years of Experience", value: "8+" },
  { label: "Enterprise Customers", value: "150+" },
  { label: "Seed Funding Raised", value: "₹8Cr" },
  { label: "Revenue Generated for Clients", value: "₹500Cr+" },
];

export const skillCategories = [
  {
    name: "Startup & Entrepreneurship",
    icon: "🚀",
    skills: [
      { name: "Startup Founding & Scaling", level: 97 },
      { name: "Venture Fundraising", level: 90 },
      { name: "Go-to-Market Strategy", level: 95 },
      { name: "Enterprise Sales", level: 92 },
      { name: "Product-Market Fit", level: 90 },
    ],
  },
  {
    name: "AI & Product",
    icon: "🤖",
    skills: [
      { name: "Agentic AI Workflows", level: 93 },
      { name: "Enterprise SaaS Product", level: 95 },
      { name: "AI Platform Strategy", level: 90 },
      { name: "Workflow Automation", level: 88 },
      { name: "LLM Application Design", level: 82 },
    ],
  },
  {
    name: "Strategy & Operations",
    icon: "📊",
    skills: [
      { name: "Strategic Management", level: 95 },
      { name: "Business Operations", level: 92 },
      { name: "P&L Ownership", level: 88 },
      { name: "Lean Operations", level: 87 },
      { name: "Management Information Systems", level: 85 },
    ],
  },
  {
    name: "Consulting & Advisory",
    icon: "💡",
    skills: [
      { name: "HR Tech Consulting (Darwinbox)", level: 88 },
      { name: "Enterprise Consulting", level: 87 },
      { name: "Client Relationship Management", level: 90 },
      { name: "Digital Transformation", level: 85 },
    ],
  },
  {
    name: "Business Development",
    icon: "🤝",
    skills: [
      { name: "B2B Enterprise Sales", level: 92 },
      { name: "Partnership Development", level: 88 },
      { name: "Customer Success", level: 90 },
      { name: "Investor Relations", level: 85 },
    ],
  },
  {
    name: "Leadership",
    icon: "🎯",
    skills: [
      { name: "Team Building & Culture", level: 90 },
      { name: "Cross-functional Leadership", level: 92 },
      { name: "Stakeholder Management", level: 93 },
      { name: "OKR & Goal Setting", level: 88 },
    ],
  },
];

export const experience = [
  {
    id: "epoch-1",
    era: "Foundation",
    period: "2014 – 2016",
    title: "MBA — Strategic Management",
    company: "XLRI Jamshedpur",
    description:
      "Completed MBA in Strategic Management at XLRI Jamshedpur — one of India's premier B-schools. Specializations in Management Information Systems, Marketing, and Lean Operations. Developed strong frameworks in business strategy, operations management, and organizational design. Achieved AIR 159 in Global Mathematical Talent Probe and was twice recommended by the Service Selection Board for the Indian Air Force and Navy.",
    tech: ["Strategic Management", "MIS", "Marketing", "Lean Operations", "Business Analytics"],
    accuracy: 0.78,
    loss: 0.22,
  },
  {
    id: "epoch-2",
    era: "Early Career",
    period: "2016 – 2019",
    title: "Business Consultant",
    company: "ADPL & Coforge",
    description:
      "Began professional career in enterprise consulting at ADPL and Coforge — building core skills in client engagement, project delivery, and digital transformation. Developed expertise in enterprise technology adoption and business process improvement across sectors.",
    tech: ["Enterprise Consulting", "Digital Transformation", "Client Engagement", "Business Analysis"],
    accuracy: 0.80,
    loss: 0.20,
  },
  {
    id: "epoch-3",
    era: "HRTech",
    period: "2020 – 2022",
    title: "Consultant",
    company: "Darwinbox",
    description:
      "Joined Darwinbox — India's fastest-growing HCM platform — as a Consultant driving enterprise HR technology adoption. Partnered with large enterprises to implement and maximize value from Darwinbox's HRMS suite covering talent management, payroll, and workforce analytics. Gained deep B2B SaaS GTM and customer success expertise.",
    tech: ["HCM / HRMS", "B2B SaaS", "Enterprise Sales", "Customer Success", "HR Technology"],
    accuracy: 0.87,
    loss: 0.13,
  },
  {
    id: "epoch-4",
    era: "Founder Mode",
    period: "2021 – Present",
    title: "Co-founder — Strategy & Operations",
    company: "Cheerio AI",
    description:
      "Co-founded Cheerio AI — an agentic AI platform for enterprise workflows across marketing, sales, support, and retention. Bootstrapped from zero to ₹8 Crore seed round (led by Artha Venture Fund II), 150+ enterprise customers across 6 industries, and ₹500+ Crore in additional revenue generated for clients. Vertoz Group acquired a minority stake. Led fundraising, go-to-market, and strategic partnerships.",
    tech: [
      "Agentic AI",
      "Enterprise SaaS",
      "Fundraising",
      "Go-to-Market",
      "Product Strategy",
      "LLM Workflows",
      "Marketing Automation",
    ],
    accuracy: 0.97,
    loss: 0.03,
  },
];

export const featuredProjects = [
  {
    id: "proj-1",
    name: "Cheerio AI Platform",
    tagline: "Agentic AI for Enterprise Workflows",
    description:
      "Built and scaled Cheerio AI — an agentic AI platform enabling complex enterprise operations across marketing, sales, support, and retention. Raised ₹8 Crore in seed funding, served 150+ enterprise customers, and generated ₹500+ Crore in client revenue. Backed by Artha Venture Fund II with Vertoz Group as minority stakeholder.",
    tech: ["Agentic AI", "LLM Workflows", "Marketing Automation", "Enterprise SaaS", "B2B Platform"],
    metrics: "150+ enterprises | ₹8Cr seed | ₹500Cr+ client revenue",
    category: "AI Startup",
    status: "Live & Scaling",
    link: "https://www.cheerioai.com",
    github: "#",
  },
  {
    id: "proj-2",
    name: "Cheerio AI Seed Round",
    tagline: "₹8 Crore — Artha Venture Fund II",
    description:
      "Led end-to-end fundraising for Cheerio AI's seed round — from pitch deck to term sheet to close. Secured ₹8 Crore from Artha Venture Fund II, positioning Cheerio as India's leading agentic AI platform for enterprise. Also structured a strategic minority stake acquisition by Vertoz Group.",
    tech: ["Fundraising", "Investor Relations", "Pitch Strategy", "Term Sheet Negotiation", "Cap Table"],
    metrics: "₹8Cr raised | Artha Venture Fund II | Vertoz Group minority stake",
    category: "Venture Fundraising",
    status: "Closed",
    link: "https://www.cheerioai.com/blogs/cheerio-ai-raises-%E2%82%B98-crore-to-build-the-future-of-agentic-ai-for-enterprise-workflows",
    github: "#",
  },
  {
    id: "proj-3",
    name: "Darwinbox Enterprise GTM",
    tagline: "B2B SaaS Go-to-Market at Scale",
    description:
      "As Consultant at Darwinbox, drove enterprise HRMS adoption at scale. Managed complex multi-stakeholder sales cycles, large-scale HCM implementations, and post-go-live customer success — contributing to Darwinbox's trajectory toward unicorn status.",
    tech: ["B2B SaaS", "Enterprise HRMS", "Customer Success", "Solution Consulting", "Stakeholder Management"],
    metrics: "Enterprise clients | Multi-stakeholder sales | HCM at scale",
    category: "HR Technology",
    status: "Past Role",
    link: "https://darwinbox.com",
    github: "#",
  },
  {
    id: "proj-4",
    name: "Thought Leadership & Community",
    tagline: "12,000+ LinkedIn Followers | AI & Startup Voice",
    description:
      "Built a personal brand of 12,298+ LinkedIn followers sharing insights on AI, enterprise SaaS, and startup building. Active voice in India's startup ecosystem on agentic AI and B2B GTM. Volunteer background: Joy of Giving Week organizer, Red Cross Youth, Juvenile Care at VIT.",
    tech: ["LinkedIn", "Content Marketing", "Thought Leadership", "Community Building", "Public Speaking"],
    metrics: "12,298+ followers | 500+ connections | Startup ecosystem",
    category: "Personal Brand",
    status: "Ongoing",
    link: "https://www.linkedin.com/in/avinashupadhyay24",
    github: "#",
  },
];

export const testimonials = [
  {
    id: "t1",
    name: "Investment Partner",
    role: "Artha Venture Fund II",
    avatar: "A",
    text: "Avinash and the Cheerio AI team bring sharp product thinking and a clear enterprise thesis. The traction with 150+ customers and ₹500Cr+ revenue impact they've enabled is a testament to both team execution and the platform's real differentiation.",
    relation: "Lead Investor, Cheerio AI Seed Round",
  },
  {
    id: "t2",
    name: "Head of Marketing",
    role: "Enterprise Client",
    avatar: "E",
    text: "Cheerio AI transformed our customer engagement workflows. What used to require a team of 10 and weeks of manual effort now runs autonomously. Avinash's team has built something genuinely differentiated in the enterprise AI space.",
    relation: "Enterprise Customer, Cheerio AI",
  },
];

export const graphNodes = [
  { id: "agenticai", label: "Agentic AI", group: "ai", size: 40 },
  { id: "llm", label: "LLM Workflows", group: "ai", size: 35 },
  { id: "enterprise", label: "Enterprise SaaS", group: "product", size: 38 },
  { id: "gtm", label: "Go-to-Market", group: "strategy", size: 34 },
  { id: "fundraising", label: "Fundraising", group: "startup", size: 30 },
  { id: "strategy", label: "Strategy", group: "strategy", size: 36 },
  { id: "ops", label: "Operations", group: "strategy", size: 28 },
  { id: "sales", label: "B2B Sales", group: "product", size: 32 },
  { id: "mba", label: "XLRI MBA", group: "education", size: 26 },
  { id: "consulting", label: "Consulting", group: "education", size: 24 },
  { id: "cheerio", label: "Cheerio AI", group: "startup", size: 42 },
];

export const projectConnections = [
  { source: "agenticai", target: "llm" },
  { source: "agenticai", target: "enterprise" },
  { source: "enterprise", target: "gtm" },
  { source: "gtm", target: "sales" },
  { source: "fundraising", target: "cheerio" },
  { source: "cheerio", target: "agenticai" },
  { source: "strategy", target: "ops" },
  { source: "mba", target: "strategy" },
  { source: "consulting", target: "gtm" },
  { source: "strategy", target: "cheerio" },
];

export const skillJourney = [
  { year: 2014, skill: "Strategic Management", milestone: "XLRI Jamshedpur MBA — Strategy & MIS" },
  { year: 2016, skill: "Enterprise Consulting", milestone: "Career begins at ADPL & Coforge" },
  { year: 2020, skill: "B2B SaaS GTM", milestone: "Consultant at Darwinbox — HR Tech at scale" },
  { year: 2021, skill: "Startup Founding", milestone: "Co-founded Cheerio AI" },
  { year: 2023, skill: "Venture Fundraising", milestone: "₹8 Crore seed — Artha Venture Fund II" },
  { year: 2024, skill: "Agentic AI", milestone: "150+ enterprises, ₹500Cr+ revenue impact" },
  { year: 2025, skill: "AI Platform Scale", milestone: "Scaling Cheerio AI across 6 industries in Asia" },
  { year: 2026, skill: "Enterprise AI Leadership", milestone: "Defining the future of agentic enterprise workflows" },
];
